{% set version = "0.0.8" %}

package:
  name: "dolang"
  version: "{{ version }}"

source:
  git_url: https://github.com/EconForge/dolang.py.git
  git_rev: v{{ version }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - numba >=0.49.0
    - numpy >=1.16
    - pip
    - python >=3.6
    - sympy >=1.5
    - tempita >=0.5.2
    - poetry

  run:
    - numba >=0.49.0
    - numpy >=1.16
    - python >=3.6
    - sympy >=1.5
    - tempita >=0.5.2

test:
  imports:
    - dolang
    - dolang.tests

about:
  home: https://github.com/EconForge/dolang.py
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: "Dolo Modeling Language"

extra:
  recipe-maintainers:
    - albop
